config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :rides
  resources :reservations
  resources :users
  resources :message_boards

  root "static_pages#home"

  get "/login", to: "users#login", as: "login"
  post "/login", to: "users#handle_login"
  delete "/logout", to: "users#logout"
 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message_board.rb
class MessageBoard < ApplicationRecord
    belongs_to :user
    belongs_to :ride

    validates :rating, numericality: {greater_than: 0, less_than: 6}
    validates :comment, presence: true
  
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :ride

    def current_status
        
        if @current_user.reservations == self
            reservation.status = "Booked"
        else
            reservation.status = "Completed"
        end

    end
end

app/models/ride.rb
class Ride < ApplicationRecord
    has_many :reservations
    has_many :users, through: :reservations

    has_many :message_boards
    has_many :users, through: :message_boards

    acts_as_commontable

    def avg_rating
        self.message_boards.distinct.average(:rating).round()
    end
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservations
    has_many :rides, through: :reservations

    has_many :message_boards
    has_many :rides, through: :message_boards

    validates :name, presence: true
    validates :email, uniqueness: true, presence: true
    validates :password, length: { in: 6..20 }
    validates :age, numericality: { greather_than: 17 }

    has_secure_password

    acts_as_commontator
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    before_action :authorized


    
    helper_method :logged_in?
    

    def set_current_user
        @current_user = User.find_by(id: session[:user])
    end

    def logged_in?
        # This method returns a boolean, depending on if there's a user logged in or not
        !!set_current_user
    end

    def authorized
        redirect_to new_user_path unless logged_in?
    end

end

app/controllers/message_boards_controller.rb
class MessageBoardsController < ApplicationController
   
        before_action :find_mess, only: [:edit, :update, :destroy]


    def index

    end

    def new
        @message_board = MessageBoard.new
    end

    def create
        message_board = @current_user.message_boards.create(mess_params)

        if message_board.valid?
           redirect_to ride_path(message_board.ride)
        else
           flash[:my_errors] = message_board.errors.full_messages
            redirect_to new_message_board_path
        end
    end

    def edit

    end

    def update
        @message_board.update(mess_params)

        
        redirect_to ride_path(@message_board.ride)
    end

    def destroy  
        @message_board.destroy
        redirect_to rides_path
    end


    private

    def mess_params
        params.require(:message_board).permit!
    end

    def find_mess 
        @message_board = MessageBoard.find(params[:id])
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

    before_action :find_res, only: [:edit, :update, :destroy]

    def new
        @reservation = Reservation.new
    end

    def create
        reservation = @current_user.reservations.create(res_params)

        if reservation.valid?
           redirect_to user_path(reservation.user)
        else
            flash[:my_errors] = reservation.errors.full_messages
            redirect_to new_reservation_path
        end
    end

    def edit
        
    end

    def update
        @reservation.update(res_params)

        redirect_to user_path(@reservation.user)
    end

    def destroy
        @reservation.destroy
        redirect_to user_path(@current_user)
    end

    private

    def res_params
        params.require(:reservation).permit(:user_id, :ride_id, :date_time, :status)
    end

    def find_res
        @reservation = Reservation.find(params[:id])
    end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
    
        before_action :find_ride, only: [:show, :edit, :update]

    def index
        @rides = Ride.all
    end

    def show
        
    end

    def edit
       
    end

    def update
        @ride.update(params.require(:ride).permit!)

        redirect_to ride_path(@ride)
    end

    private

    def find_ride
        @ride = Ride.find(params[:id])
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :authorized, only: [:new, :create, :login, :handle_login]


    def show
        
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)

        if @user.valid?
            session[:user] = @user.id
            redirect_to user_path(@user)
        else
            flash[:my_errors] = @user.errors.full_messages
            redirect_to new_user_path
        end

    end

    def edit

    end

    def update
        @user.update(user_params)
        
        redirect_to user_path(@user)
    end

    def login
        
    end

    def handle_login
        # params is a hash, with keys provided by the form_tag
        # the values of params is coming from the user-input

        @user = User.find_by(name: params[:name])

        if @user && @user.authenticate(params[:password])
            session[:user] = @user.id
            redirect_to root_path
        else
            flash[:message] = "Incorrect Username or Password"
            redirect_to login_path
        end
    end

    def logout
        session[:user] = nil
        redirect_to login_path
    end

    def destroy
        @user.destroy
        redirect_to login_path
    end


    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :age, :image, :email, :password, :password_confirmation)
    end
    


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_boards_helper.rb
module MessageBoardsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateAdventure</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>




  <body>
  <% if logged_in? %>
     <div class="topnav">
     <a> <%= link_to "Home", root_path %> </a>
     <a> <%= link_to "Rides", rides_path %> </a>
     <a> <%= link_to "Reservation", new_reservation_path %> </a>
     <a> <%= link_to "Profile", user_path(@current_user) %> </a>
     <a> <%= link_to "Rate Ride", new_message_board_path %> </a>
     <a> <%= link_to "Sign Out", "/logout", method: :delete %></a>
     <a> Logged in as: <%=  @current_user.name%> </a>
  
     <% end %>
 
    </div>
      
     
    <%= yield %>
  </body>
</html>

app/views/message_boards/_form.html.erb
<% if flash[:my_errors] %>
    <% flash[:my_errors].each do |er| %>
         <%= er %> 
    <% end %>

<% end %>

<h1 class = "h1-res"> Rate Ride</h1>
<div class= "reservation">
  <%= form_for @message_board do |f| %>
    <h3><%= f.label :ride_id %></h3>
    <%= f.collection_select :ride_id, Ride.all, :id, :name %><br><br>
    <%= f.label :rating %>
    <%= f.number_field :rating %><br><br>
    <%= f.label :comment %>
    <%= f.text_area :comment %><br><br>
    
    <%= f.submit "comment", class:"myClass"%>
 <% end %>
</div>

app/views/message_boards/edit.html.erb
<%= render "form" %>

app/views/message_boards/new.html.erb
<%= render "form" %>

app/views/reservations/_form.html.erb
<div class= "reservation">
 <%= form_for @reservation do |f| %><br>
 <h1><%= f.label :ride_id %><br></h1>
 <%= f.collection_select :ride_id, Ride.all, :id, :name %><br>

 <h3>Time: <%= f.time_field :date_time, as: :time, value: f.object.try(:strftime,"%h:%h:%s %z"), class: 'form-control' %><br><br></h3>

 <h3> Date: <%= f.date_field :date_time, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %><br><br></h3>


 <%= f.submit class:"myClass" %>
 <% end %>
</div>

app/views/reservations/edit.html.erb
<%= render "form" %>

app/views/reservations/new.html.erb
<h1 class = "h1-res"> New Reservation </h1>


<%= render "form" %>

app/views/rides/index.html.erb
<div class="index-container">
  <% @rides.each do |ride| %>
     <div class="index-card">
      <h2><%= link_to ride.name, ride_path(ride) %></h2>
      <img src="<%= ride.image %>" alt="<%ride.name%>"  style="width:50%" , class="index-img">
    </div>
  <% end %>
</div>

app/views/rides/show.html.erb
  <div class="card">
  <h1><b> Name: <%= @ride.name %> </b></h1> 
  
  <div class="container">
  <img src= "<%= @ride.image %>" alt="<%= @ride.name%>" style="width:50%">
    <h3><p> Description: </h3> <%= @ride.description %></p>
    <h3> Capacity: <%=@ride.capacity %></h3> 
  </div>
</div>
 <h1><strong> Comments/Ratings: </strong></h1>
<ul>
  <% @ride.message_boards.each do |mess| %>
       <li> 
          <b><%= mess.user.name %> </b><br>
            Rating: <%= mess.rating %> <br>
             <%= mess.comment %> 
           <% if @current_user == mess.user %>
            <%= button_to "Delete", message_board_path(mess), method: :delete, class:"myClass"%> <%= button_to "Update", edit_message_board_path(mess), method: :get, class:"myClass"%>
            
          <% end %>
        </li>
    <% end %>

  </ul>


  


  

  

app/views/static_pages/home.html.erb
  <h1 class="home-h1"> 🎠Rate Adventure🎢</h1>
  <div class ="home-page">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/RB89R41R7f4?start=97" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
 

  

  

app/views/users/_form.html.erb
<% if flash[:my_errors] %>
<ul>
    <% flash[:my_errors].each do |er| %>
        <li> <%= er %> </li>
    <% end %>
<% end %>
</ul>
<div class= "reservation">
 <%= form_for @user do |f| %>
    <%= f.label :name %> <br>
    <%= f.text_field :name %><br>
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
    <%= f.label :age %><br>
    <%= f.number_field :age %><br>
    <%= f.label :image %><br>
    <%= f.text_field :image %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit class: "myClass"%>
 <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

<%= button_to "Delete Account?", user_path, method: :delete, class:"myClass1" %>

app/views/users/login.html.erb
<div class= "background-image">
  <h1 class= "login-h1">Welcome to Rate Adventure</h1>
</div>
<% if flash[:message] %>
   <p class="flash"> <%= flash[:message] %> </p>
<% end %>
 <div class="login" >
    <%= form_tag "/login" do  %>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
<p class= "button"><%= submit_tag "Log in!" %></p>
    <% end %>
 </div>

  <p class = "new-user">New user? <%= link_to "Sign up now!", new_user_path %></p>

app/views/users/new.html.erb
<h1>Sign up for Rate Adventure</h1>



<%= render 'form' %>

app/views/users/show.html.erb
<div class="card">
  <img src= "<%= @user.image %>" alt="<%= @user.name%>" style="width:50%; border-radius: 50%; box-shadow: 0 4px 8px 0 rgb(142 0 255 / 76%);">
  <div class="container">
    <h1><b><%= @user.name %> </b></h1> 
    <h3> Age: <%=@user.age %></h3> 
    <%= button_to 'Update Info', edit_user_path(@current_user), method: :get, class:"myClass" %>
  </div>
</div>


<div class="resevation">
<h1>Reservations</h1>
</div>




<div class="main-div">
    <% @user.reservations.each do |res| %>
        <h1 class ="ride-h1"><%= link_to res.ride.name, ride_path(res.ride) %></h1><br>
       <img src="<%= res.ride.image %>" alt="<%= res.ride.image%>" style="width:60%"><br>

        <h3> Reservation Time: <%= res.date_time.strftime(" %m/%d/%Y at %I:%M")%></h3> <br>
        <%= button_to 'Update Reservation', edit_reservation_path(res), method: :get, class:"myClass" %>
        
            <%= link_to res, method: :delete, data: {confirm: "Are You Sure?"} do%>
              <div class="mydelete" >
                Delete?
                <br>
                </div>
           
            <%end%>
          
    <%end%>
</div>
 